"use client";
import {useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/shell';
import NoteReader from '@/components/note-reader';
import {departments} from '@/data/courses';
import {politicalScienceDetails} from '@/data/politicalScience';
import {notesForDepartment,syllabusResources} from '@/data/notes';
import {download,emptyList,isString,isStringList,useSaved} from '@/lib/storage';
function CourseNotes({courseKey,title}:{courseKey:string;title:string}){const notes=useSaved(`course-notes:${courseKey}`,'',isString);return <div className="section-gap"><label htmlFor={`notes-${courseKey}`}>My notes for {title}</label><textarea id={`notes-${courseKey}`} rows={5} value={notes.value} onChange={e=>notes.setValue(e.target.value)} placeholder="Key ideas, questions for class and sources…"/><button className="btn secondary section-gap" disabled={!notes.value.trim()} onClick={()=>download(`${courseKey.replace(/[^a-z0-9]/gi,'-')}-notes.txt`,`${title}\n\n${notes.value}`)}>Download notes</button>{notes.error&&<p role="alert" className="notice error">{notes.error}</p>}</div>}
export default function College(){const [department,setDepartment]=useState(departments[0].id);const [semester,setSemester]=useState(1);const [query,setQuery]=useState('');const done=useSaved('topics',emptyList,isStringList);const saved=useSaved('bookmarks',emptyList,isStringList);const [bookmarksOnly,setBookmarksOnly]=useState(false);
 const all=departments.flatMap(d=>d.semesters.flatMap(s=>s.courses.map(c=>({...c,department:d.id,departmentName:d.name,semester:s.semester,key:`${d.id}:${s.semester}:${c.code}`}))));
 const searching=query.trim().length>0;
 const list=all.filter(c=>(searching?`${c.title} ${c.code} ${c.departmentName}`.toLowerCase().includes(query.trim().toLowerCase()):c.department===department&&c.semester===semester)&&(!bookmarksOnly||saved.value.includes(c.key)));
 const current=departments.find(d=>d.id===department)!;
 const currentNotes=notesForDepartment(department);
 const syllabus=syllabusResources.find(resource=>resource.department===department);
 function noteForCourse(course:{code:string;semester:number;department:string}){
  const courseNotes=notesForDepartment(course.department);
  if(course.department==='vac') return courseNotes.find(note=>note.id===`vac-${Number(course.code.replace(/\D/g,''))-100}`);
  const batch=course.semester<=2?1:course.semester<=4?2:course.semester<=6?3:0;
  return batch?courseNotes.find(note=>note.id===`${course.department}-${batch}`):undefined;
 }
 return <Shell eyebrow="College hub" title="Your subjects. Your study plan." intro="Browse the official course catalogue, use the TRC guides you prepared and keep your own notes beside each paper."><div className="notice">If you are not taking a subject, you do not need to study it. The course list and syllabus links below come from the supplied MZU documents. Use the official syllabus and your teacher’s instructions when preparing for an examination.</div><section className="panel section-gap"><div className="two-col"><div><label htmlFor="department">Department</label><select id="department" value={department} onChange={e=>{setDepartment(e.target.value);setSemester(1);setQuery('');}}>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div><label htmlFor="semester">Semester</label><select id="semester" value={semester} onChange={e=>{setSemester(Number(e.target.value));setQuery('');}}>{current.semesters.map(s=><option key={s.semester} value={s.semester}>Semester {s.semester}</option>)}</select></div></div><div className="section-gap"><label htmlFor="course-search">Search all departments and semesters</label><input id="course-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Paper title, code or department" type="search"/></div><label className="check-row"><input type="checkbox" checked={bookmarksOnly} onChange={e=>setBookmarksOnly(e.target.checked)}/>Only bookmarked papers in these results</label><p className="small muted" role="status">{list.length} papers {searching?'across the catalogue':`in ${current.name}, semester ${semester}`}</p></section>
 <NoteReader key={`${department}-${semester}`} resources={[...currentNotes].sort((a,b)=>Number(b.id===noteForCourse({department,semester,code:`VAC ${100+semester}`})?.id)-Number(a.id===noteForCourse({department,semester,code:`VAC ${100+semester}`})?.id))}/>
 <section className="panel section-gap"><div className="row between"><div><p className="eyebrow">Reference document</p><h2>Official syllabus</h2></div>{syllabus&&<a className="btn secondary" href={syllabus.file} target="_blank" rel="noreferrer">Open official syllabus ↗</a>}</div><p className="muted">Read the prepared notes above. The guides cover Semesters I–VI, with separate VAC guides. Use the official syllabus to confirm your paper’s complete unit list.</p>{!syllabus&&<p className="notice">An official Economics PDF was not included with the supplied files. Confirm the current Economics syllabus with your department.</p>}</section>
 {(done.error||saved.error)&&<p className="notice error" role="alert">{done.error||saved.error}</p>}
 <div className="stack section-gap">{list.length===0&&<section className="panel"><h2>No matching papers</h2><p className="muted">Try a different search, department or semester, or turn off the bookmark filter.</p><button className="btn secondary" onClick={()=>{setQuery('');setBookmarksOnly(false);}}>Clear search and bookmark filter</button></section>}{list.map(course=>{const detail=course.department==='political-science'?politicalScienceDetails.find(c=>c.code===course.code):undefined;const paperNote=noteForCourse(course);const total=detail?.units.reduce((n,u)=>n+u.topics.length,0)??0;const completed=detail?.units.reduce((n,u,ui)=>n+u.topics.filter((_,ti)=>done.value.includes(`${course.key}:${ui}:${ti}`)).length,0)??0;
 return <article className="panel" key={course.key}><div className="row between"><span className="eyebrow">{course.code} · Semester {course.semester}</span><button className="btn secondary" aria-pressed={saved.value.includes(course.key)} onClick={()=>saved.setValue(saved.value.includes(course.key)?saved.value.filter(x=>x!==course.key):[...saved.value,course.key])}>{saved.value.includes(course.key)?'★ Bookmarked':'☆ Bookmark'}</button></div><h2>{course.title}</h2><p className="small muted">{course.departmentName} · {course.category} · {course.credits??'—'} credits</p>
 {detail?<><p className="small muted">{completed} / {total} topics studied</p><progress value={completed} max={total||1} aria-label={`${course.title} study progress`}/><details><summary>Open syllabus and study checklist</summary>{detail.units.map((unit,ui)=><section className="section-gap" key={unit.title}><h3>{unit.title}</h3>{unit.topics.map((topic,ti)=>{const id=`${course.key}:${ui}:${ti}`;return <label key={id} className="check-row"><input type="checkbox" checked={done.value.includes(id)} onChange={e=>done.setValue(e.target.checked?[...done.value,id]:done.value.filter(x=>x!==id))}/>{topic}</label>})}</section>)}</details></>:<p className="notice">Use the official syllabus link above for the complete unit list, then download the prepared guide for this subject. You can make your own checklist and notes below. The <Link href="/study" className="accent underline">PDF Study Lab</Link> can keep the syllabus open while you study.</p>}
 {paperNote&&<p className="notice"><strong>Prepared guide:</strong> <Link className="accent underline" href={`/notes/${paperNote.id}`}>Read {paperNote.label} online ↗</Link> · <a className="accent underline" href={paperNote.file} download>Download</a></p>}<details><summary>My paper notes</summary><CourseNotes courseKey={course.key} title={course.title}/></details></article>})}</div></Shell>}
