"use client";
import {useEffect,useState} from 'react';
import Shell from '@/components/shell';
import {download,useSaved} from '@/lib/storage';
type Card={id:string;front:string;back:string};
type Notebook={id:string;title:string;notes:string;cards:Card[]};
const initial:Notebook[]=[{id:'first',title:'My first notebook',notes:'',cards:[]}];
function isNotebooks(v:unknown):v is Notebook[]{return Array.isArray(v)&&v.length>0&&v.length<=100&&new Set(v.map(n=>n?.id)).size===v.length&&v.every(n=>n&&typeof n.id==='string'&&typeof n.title==='string'&&typeof n.notes==='string'&&Array.isArray(n.cards)&&n.cards.length<=500&&n.cards.every((c:Card)=>c&&typeof c.id==='string'&&typeof c.front==='string'&&typeof c.back==='string'));}
export default function Study(){
 const books=useSaved('notebooks',initial,isNotebooks);const [selected,setSelected]=useState('first');const book=books.value.find(n=>n.id===selected)??books.value[0];
 const [pdf,setPdf]=useState<File|null>(null);const [url,setUrl]=useState('');const [message,setMessage]=useState('');const [front,setFront]=useState('');const [back,setBack]=useState('');const [flipped,setFlipped]=useState<string[]>([]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]); // Release local PDF URLs when replaced or unmounted.
 function update(patch:Partial<Notebook>){books.setValue(books.value.map(n=>n.id===book.id?{...n,...patch}:n));}
 async function openPdf(file?:File){if(!file)return;try{if(file.size>25*1024*1024)throw Error('Choose a PDF smaller than 25 MB.');const header=await file.slice(0,1024).text();if(!header.includes('%PDF-'))throw Error('This file does not look like a PDF.');setPdf(file);setUrl(URL.createObjectURL(file));setMessage('PDF opened on this device. Re-select the file after refreshing.');}catch(e){setMessage(e instanceof Error?e.message:'Could not open this PDF.');}}
 async function restore(file?:File){if(!file)return;try{if(file.size>2*1024*1024)throw Error('Choose a notebook backup smaller than 2 MB.');const parsed:unknown=JSON.parse(await file.text());if(!isNotebooks(parsed))throw Error('Choose a valid notebook JSON backup.');if(!confirm('Replace all current notebooks with this backup? Download your current notebooks first if you need them.'))return;books.setValue(parsed);setSelected(parsed[0].id);setMessage('Notebooks restored.');}catch(e){setMessage(e instanceof Error?e.message:'Restore failed.');}}
 return <Shell eyebrow="PDF study lab" title="Read. Make sense of it. Remember." intro="Open your own PDF, write notes in simple words and make revision cards. Your document stays on your device.">
 <div className="two-col"><section className="panel"><h2>Your reading</h2><label htmlFor="pdf-file">Open a PDF (up to 25 MB)</label><input id="pdf-file" type="file" accept="application/pdf,.pdf" onChange={e=>{void openPdf(e.target.files?.[0]);e.target.value='';}}/>{url?<><p className="small muted">{pdf?.name}</p><object data={url} type="application/pdf" aria-label="PDF document" style={{width:'100%',height:650,background:'#fff',marginTop:16,borderRadius:8}}><p style={{padding:20,color:'#111'}}>Your browser cannot display this PDF here. Use the open button below.</p></object><a className="btn secondary section-gap" href={url} target="_blank" rel="noreferrer">Open PDF in a new tab ↗</a></>:<div className="notice section-gap"><strong>Bring your study material.</strong><p>Choose a syllabus, chapter or handout. Read one section, then explain it in your own words in the notebook beside it.</p><p>No automatic AI summaries or PDF extraction are used. The notes and cards are written by you.</p></div>}<p className="small muted">The PDF itself is not saved. Keep the original file and reopen it next time. Phone browsers may show it in a separate tab.</p></section>
 <section className="panel"><h2>Your notebook</h2><label htmlFor="notebook">Choose notebook</label><select id="notebook" value={book.id} onChange={e=>{setSelected(e.target.value);setFront('');setBack('');}}>{books.value.map(n=><option key={n.id} value={n.id}>{n.title||'Untitled notebook'}</option>)}</select><div className="row section-gap"><button className="btn secondary" disabled={books.value.length>=100} onClick={()=>{const id=crypto.randomUUID();books.setValue([...books.value,{id,title:`Notebook ${books.value.length+1}`,notes:'',cards:[]}]);setSelected(id);setFront('');setBack('');}}>New notebook</button><button className="btn danger" disabled={books.value.length===1} onClick={()=>{if(confirm(`Delete “${book.title}” and its cards?`)){books.setValue(books.value.filter(n=>n.id!==book.id));setSelected(books.value.find(n=>n.id!==book.id)!.id);}}}>Delete notebook</button></div><div className="section-gap"><label htmlFor="notebook-title">Title</label><input id="notebook-title" maxLength={120} value={book.title} onChange={e=>update({title:e.target.value})}/></div><div className="section-gap"><label htmlFor="study-notes">Notes</label><textarea id="study-notes" rows={14} maxLength={100000} value={book.notes} onChange={e=>update({notes:e.target.value})} placeholder="Page number and topic\nWhat does it mean?\nAn example in my own words\nA question to ask in class\nSource / author / year"/></div><p className="small muted">Saved in this browser as you type. Download a backup before clearing browser data or changing devices.</p><button className="btn secondary" onClick={()=>download('study-notes.txt',`${book.title}\n\n${book.notes}\n\nREVISION CARDS\n${book.cards.map(c=>`${c.front}\n${c.back}`).join('\n\n')}`)}>Download this notebook as text</button>{books.error&&<p role="alert" className="notice error">{books.error}</p>}</section></div>
 <section className="panel section-gap"><p className="eyebrow">Recall before you reveal</p><h2>Revision cards for {book.title||'this notebook'}</h2><form onSubmit={e=>{e.preventDefault();if(!front.trim()||!back.trim())return;update({cards:[...book.cards,{id:crypto.randomUUID(),front:front.trim(),back:back.trim()}]});setFront('');setBack('');}}><div className="two-col"><div><label htmlFor="card-front">Question or key term</label><input id="card-front" required maxLength={300} value={front} onChange={e=>setFront(e.target.value)} placeholder="What is positive liberty?"/></div><div><label htmlFor="card-back">Answer in your own words</label><textarea id="card-back" required maxLength={3000} rows={2} value={back} onChange={e=>setBack(e.target.value)} placeholder="Write the explanation you want to remember."/></div></div><button className="btn section-gap" disabled={book.cards.length>=500}>Add revision card</button></form>{book.cards.length===0&&<p className="muted">No cards yet. Turn one important idea from your reading into a question.</p>}<div className="grid-cards section-gap">{book.cards.map(c=><article className="panel" key={c.id}><h3>{c.front}</h3>{flipped.includes(c.id)&&<p>{c.back}</p>}<div className="row section-gap"><button className="btn secondary" onClick={()=>setFlipped(flipped.includes(c.id)?flipped.filter(id=>id!==c.id):[...flipped,c.id])}>{flipped.includes(c.id)?'Hide answer':'Reveal answer'}</button><button className="btn danger" aria-label={`Delete card: ${c.front}`} onClick={()=>{if(confirm('Delete this revision card?'))update({cards:book.cards.filter(card=>card.id!==c.id)});}}>Delete</button></div></article>)}</div></section>
 <section className="panel section-gap"><h2>Back up your study space</h2><button className="btn" onClick={()=>download('study-notebooks.json',JSON.stringify(books.value,null,2),'application/json')}>Download all notebooks and cards</button><div className="section-gap"><label htmlFor="restore-notebooks">Restore a notebook backup (.json)</label><input id="restore-notebooks" type="file" accept=".json,application/json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value='';}}/></div></section><p className="notice section-gap" role="status">{message||'Select a PDF or start writing. No account is needed.'}</p>
 </Shell>;
}
