import Link from "next/link";
const labs = [
  ["01", "</>", "Coding Lab", "Build a website, calculator or quiz. Edit your code, run it and keep a copy.", "/coding", "5 starter projects"],
  ["02", "▤", "College Hub", "Find your department and semester. Follow your syllabus and keep study notes.", "/college", "7 subjects + VAC"],
  ["03", "▧", "PDF Study Lab", "Read your own PDF beside your notes. Turn key ideas into revision cards.", "/study", "Your own study space"],
  ["04", "◇", "Reasoning Lab", "Find patterns, follow clues and test your reasoning with clear explanations.", "/reasoning", "Practice + test mode"],
  ["05", "↗", "Driving Lab", "Understand vehicle controls, road awareness and safer decisions before practical lessons.", "/driving", "Learn the basics"],
  ["06", "⌘", "Basic Skills", "Get comfortable with files, email, spreadsheets, online safety and job applications.", "/skills", "Everyday confidence"],
  ["07", "ϟ", "Electrical Basics", "Understand circuits, power and household safety. Explore a simple virtual circuit.", "/electrical", "Learn safely"],
];
export default function Home() { return <main id="main-content" className="page">
  <section className="hero"><div><p className="eyebrow">Made for curious minds</p><h1>Learn something.<br/><span className="accent">Make it yours.</span></h1><p className="intro">Practical skills, college learning and room to experiment. Start small. Understand what you do. Build from there.</p><div className="row section-gap"><a href="#labs" className="btn">Explore the labs ↗</a><Link href="/progress" className="btn secondary">My progress</Link></div><p className="small muted section-gap">Free to use. No account. At your own pace.</p></div><div className="hero-art" aria-label="Learn, try, understand, build"><p className="eyebrow">The way we learn</p><div className="big">LEARN.<br/>TRY.<br/>BUILD.</div><p>You do not have to know everything.<br/>Start with one thing you want to understand.</p><div className="row between"><span className="tag">T. ROMANA</span><span className="accent">↗</span></div></div></section>
  <section id="labs"><div className="row between" style={{marginBottom:22}}><h2>Find your starting point</h2><span className="muted small">Seven ways to learn</span></div><div className="grid-cards">{labs.map(([n,icon,title,desc,href,tag])=><Link href={href} key={href} className="lab-card"><div className="card-top"><span className="card-icon" aria-hidden="true">{icon}</span><span>{n} / LAB</span></div><h2>{title}</h2><p>{desc}</p><div className="row between card-link"><span>{tag}</span><span aria-hidden="true">↗</span></div></Link>)}</div></section>
  <section className="roots"><div><p className="eyebrow">Know your own</p><h2>MIZO.</h2></div><div><p className="intro">Technology can help us learn about the world. But we should never become strangers to our own.</p><p className="muted">Study the Mizo language. Read Mizo literature. Know our history, culture and society. Some knowledge prepares you for an examination. Some knowledge tells you who you are.</p></div></section>
</main>; }
