"use client";
import { useEffect, useRef, useState } from "react";
import { MusicAudio } from "@/lib/music-audio";
import { download, useSaved } from "@/lib/storage";
const TRACKS=["Kick","Snare","Hi-hat","Clap"];
const pattern=(kind:string)=>TRACKS.map((_,r)=>Array.from({length:16},(_,s)=>kind==="empty"?false:r===0?s%8===0:r===1?s%8===4:r===2?s%(kind==="dance"?1:2)===0:kind==="dance"&&s%8===4));
const INITIAL=pattern("rock");
const valid=(v:unknown):v is boolean[][]=>Array.isArray(v)&&v.length===4&&v.every(row=>Array.isArray(row)&&row.length===16&&row.every(x=>typeof x==="boolean"));
export default function BeatMaker(){
  const saved=useSaved("beat-pattern",INITIAL,valid),[playing,setPlaying]=useState(false),[step,setStep]=useState(-1),[bpm,setBpm]=useState(90),[message,setMessage]=useState("");
  const audio=useRef<MusicAudio|null>(null),notes=useRef(saved.value);
  useEffect(()=>{notes.current=saved.value;},[saved.value]);
  useEffect(()=>{if(!playing)return;let n=0;const tick=()=>{notes.current.forEach((track,r)=>{if(track[n])audio.current?.drum(TRACKS[r]);});setStep(n);n=(n+1)%16;};tick();const timer=setInterval(tick,60000/bpm/4);return()=>clearInterval(timer);},[playing,bpm]);
  useEffect(()=>{const stop=()=>{if(document.hidden)setPlaying(false);};document.addEventListener("visibilitychange",stop);return()=>{document.removeEventListener("visibilitychange",stop);void audio.current?.close();audio.current=null;};},[]);
  async function toggle(){if(playing){setPlaying(false);setStep(-1);return;}try{audio.current??=new MusicAudio();await audio.current.enable();audio.current.volume=.45;setPlaying(true);setMessage("");}catch{setMessage("Sound could not start. Check browser audio permissions and tap Play again.");}}
  return <section className="panel beat-maker"><div className="row between"><div><p className="eyebrow">Make music / 16-step sequencer</p><h2>Build your own rhythm.</h2></div><span className="tag">4 beats · 4 subdivisions each</span></div><p className="muted">Tap squares to place sounds, then play your loop. The four groups represent beats 1–2–3–4. Start with kick on 1 and 3, and snare on 2 and 4.</p><div className="sequencer-scroll"><div className="sequencer-grid"><div className="sequence-label">COUNT</div>{Array.from({length:16},(_,i)=><span className="sequence-count" key={i}>{i%4===0?i/4+1:["","e","&","a"][i%4]}</span>)}{TRACKS.map((track,r)=><div className="sequence-row" key={track}><strong className="sequence-label">{track}</strong>{saved.value[r].map((on,s)=><button className={`sequence-step ${on?"on":""} ${playing&&step===s?"current":""}`} aria-label={`${track}, step ${s+1}`} aria-pressed={on} key={s} onClick={()=>saved.setValue(saved.value.map((row,i)=>i===r?row.map((v,j)=>j===s?!v:v):row))}/>)}</div>)}</div></div><div className="row section-gap"><button className="btn" onClick={()=>void toggle()}>{playing?"Stop loop":"Play loop"}</button><label>Tempo · {bpm} BPM<input type="range" min="45" max="160" value={bpm} onChange={e=>setBpm(+e.target.value)}/></label><button className="btn secondary" onClick={()=>{if(confirm("Replace your pattern with the starter beat?"))saved.setValue(pattern("rock"));}}>Starter beat</button><button className="btn secondary" onClick={()=>{if(confirm("Clear every step?"))saved.setValue(pattern("empty"));}}>Clear grid</button><button className="btn secondary" onClick={()=>download("my-beat.json",JSON.stringify({bpm,tracks:TRACKS,pattern:saved.value},null,2),"application/json")}>Export pattern</button></div><label className="section-gap">Restore a pattern (.json)<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;try{if(file.size>10000)throw Error();const parsed=JSON.parse(await file.text());if(!valid(parsed.pattern)||!Number.isInteger(parsed.bpm)||parsed.bpm<45||parsed.bpm>160)throw Error();if(confirm("Replace your current pattern?")){setPlaying(false);setBpm(parsed.bpm);saved.setValue(parsed.pattern);setMessage("Pattern restored.");}}catch{setMessage("Use a pattern backup exported by this sequencer.");}}}/></label><p className="small muted">Pattern edits save on this device. Export saves the notes, not an audio recording. Playback timing depends on your browser; keep this tab in view.</p>{message&&<p role="status">{message}</p>}{saved.error&&<p role="alert">{saved.error}</p>}</section>;
}
