"use client";
import { useState } from "react";
import { circuitReadings, type CircuitMode } from "@/lib/circuit-engine";
import { download, emptyList, isStringList, useSaved } from "@/lib/storage";
const TASKS = [
  { id:"series",title:"Share the voltage",text:"Build a closed series circuit with 6 V, R1 = 200 Ω and R2 = 100 Ω. Measure from B to C: the second resistor should have 2 V across it." },
  { id:"parallel",title:"Discover two paths",text:"Build a closed parallel circuit with 6 V and two 300 Ω resistors. Each branch should carry 20 mA; the supply should deliver 40 mA." },
  { id:"open",title:"Break the path",text:"Open the switch. Verify that total current is zero, even though the battery still has voltage between A and C." },
];
type Node = "A" | "B" | "C";
export default function CircuitWorkbench() {
  const [mode,setMode]=useState<CircuitMode>("series"),[volts,setVolts]=useState(6),[r1,setR1]=useState(200),[r2,setR2]=useState(100),[closed,setClosed]=useState(true);
  const [red,setRed]=useState<Node>("A"),[black,setBlack]=useState<Node>("C"),[lead,setLead]=useState("red"),[task,setTask]=useState(0),[feedback,setFeedback]=useState("");
  const saved=useSaved("circuit-missions",emptyList,isStringList),value=circuitReadings(volts,r1,r2,mode,closed);
  const reading=value.nodes[red]-value.nodes[black];
  const completed=TASKS.filter(t=>saved.value.includes(t.id));
  function check(){
    const success=task===0?mode==="series"&&closed&&volts===6&&r1===200&&r2===100&&red==="B"&&black==="C":task===1?mode==="parallel"&&closed&&volts===6&&r1===300&&r2===300:!closed&&red==="A"&&black==="C";
    if(success){if(!saved.value.includes(TASKS[task].id))saved.setValue([...saved.value,TASKS[task].id]);setFeedback("Verified. Compare the meter with the equations below, then try the next mission.");}else setFeedback("Not yet. Check the circuit layout, resistor values, switch and requested meter points.");
  }
  return <section className="panel circuit-workbench" aria-label="Interactive circuit workbench"><div className="row between"><div><p className="eyebrow">Electrical / build & measure</p><h2>Your virtual workbench</h2></div><span className="tag">1–12 V ideal DC model</span></div><p className="muted">Change the circuit, choose the meter points and see how voltage, resistance and current relate. All connections here are virtual.</p>
    <div className="bench-layout"><div className="bench-board"><div className="row between"><div className="tabs" role="group" aria-label="Circuit layout">{(["series","parallel"] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setFeedback("");}}>{m}</button>)}</div><button className="btn secondary" aria-pressed={closed} onClick={()=>{setClosed(!closed);setFeedback("");}}>{closed?"Open switch":"Close switch"}</button></div>
      <svg className={closed?"circuit-live":""} viewBox="0 0 620 350" role="img" aria-label={`${mode} circuit; ${closed?"closed":"open"} switch. A battery positive, B ${mode==="series"?"midpoint":"branch supply"}, C battery negative.`}>
        <defs><pattern id="bench-grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#789291" opacity=".35"/></pattern><linearGradient id="resistor-metal" x2="0" y2="1"><stop stopColor="#d9b983"/><stop offset=".5" stopColor="#f7e0a7"/><stop offset="1" stopColor="#aa8657"/></linearGradient></defs><rect width="620" height="350" fill="url(#bench-grid)"/>
        <path className="circuit-wire" d={mode==="series"?"M80 140 V70 H180 M230 70 H290 M370 70 H450 M530 70 H560 V280 H80 V205":"M80 140 V70 H180 M230 70 H280 V110 H335 M415 110 H560 V280 H80 V205 M280 110 V220 H335 M415 220 H560 V110"}/>
        <path d="M80 145 V200 M55 162 H105 M65 185 H95" stroke="#e7f1da" strokeWidth="5"/><text x="23" y="236">{volts} V</text>
        <circle cx="180" cy="70" r="5" fill="#d9edba"/><circle cx="230" cy="70" r="5" fill="#d9edba"/><path d={closed?"M180 70 H230":"M180 70 L225 40"} stroke="#d9edba" strokeWidth="5"/>
        {[{x:mode==="series"?290:335,y:mode==="series"?53:93,r:r1,n:1},{x:mode==="series"?450:335,y:mode==="series"?53:203,r:r2,n:2}].map(p=><g key={p.n}><rect x={p.x} y={p.y} width="80" height="34" rx="9" fill="url(#resistor-metal)" stroke="#f6e5c6"/><path d={`M${p.x+18} ${p.y+1}v32 M${p.x+35} ${p.y+1}v32 M${p.x+60} ${p.y+1}v32`} stroke={p.n===1?"#7d5039":"#324f83"} strokeWidth="7"/><text x={p.x} y={p.y-12}>R{p.n} · {p.r} Ω</text></g>)}
        {[{id:"A",x:125,y:70},{id:"B",x:mode==="series"?410:280,y:mode==="series"?70:110},{id:"C",x:125,y:280}].map(p=><g key={p.id}><circle cx={p.x} cy={p.y} r="10" fill="#172b31" stroke={red===p.id?"#ff9b8a":black===p.id?"#d6e3ed":"#e6c78f"} strokeWidth="4"/><text x={p.x-5} y={p.y+30}>{p.id}</text></g>)}
        <text x="210" y="324">{closed?"Conventional current: + to −":"Open path · no current"}</text>
      </svg><div className="probe-controls"><span>Place the</span><button className="probe red" aria-pressed={lead==="red"} onClick={()=>setLead("red")}>Red lead</button><button className="probe black" aria-pressed={lead==="black"} onClick={()=>setLead("black")}>Black lead</button><span>on</span>{(["A","B","C"] as const).map(n=><button className="probe" key={n} onClick={()=>lead==="red"?setRed(n):setBlack(n)}>Point {n}</button>)}</div>
      <p className="small muted">A: battery +. C: battery −. B: {mode==="series"?"junction between R1 and R2":"rail supplying both branches"}. Open-switch readings use an ideal model without stray currents.</p></div>
      <div className="bench-controls"><div className="virtual-meter"><span>DC VOLTAGE / RED {red} · BLACK {black}</span><strong>{reading.toFixed(2)} V</strong><p>{reading<0?"Negative: the leads are reversed relative to the voltage.":red===black?"Both leads are on the same point.":"Difference in potential between the selected points."}</p></div>
        <label>Supply · {volts} V<input type="range" min="1" max="12" value={volts} onChange={e=>{setVolts(+e.target.value);setFeedback("");}}/></label><label>R1 · {r1} Ω<input type="range" min="100" max="1000" step="100" value={r1} onChange={e=>{setR1(+e.target.value);setFeedback("");}}/></label><label>R2 · {r2} Ω<input type="range" min="100" max="1000" step="100" value={r2} onChange={e=>{setR2(+e.target.value);setFeedback("");}}/></label>
        <div className="bench-readings"><div><small>Total current</small><strong>{(value.current*1000).toFixed(1)} mA</strong></div><div><small>Resistor network</small><strong>{value.resistance.toFixed(1)} Ω</strong></div><div><small>R1 current</small><strong>{(value.i1*1000).toFixed(1)} mA</strong></div><div><small>R2 current</small><strong>{(value.i2*1000).toFixed(1)} mA</strong></div><div><small>R1 / R2 voltage</small><strong>{value.v1.toFixed(2)} / {value.v2.toFixed(2)} V</strong></div><div><small>Supply power</small><strong>{value.power.toFixed(3)} W</strong></div></div>
      </div></div>
    <div className="bench-mission"><div><p className="eyebrow">Guided experiments · {completed.length}/3 verified</p><label>Choose a mission<select value={task} onChange={e=>{setTask(+e.target.value);setFeedback("");}}>{TASKS.map((t,i)=><option value={i} key={t.id}>{i+1}. {t.title}{saved.value.includes(t.id)?" ✓":""}</option>)}</select></label><p>{TASKS[task].text}</p></div><button className="btn" onClick={check}>Check my circuit</button></div><p role="status">{feedback}</p>
    <details><summary>Explain the numbers</summary><p>Ohm’s law: I = V ÷ R. Series resistances add; the same current passes through both. In parallel, 1/R = 1/R1 + 1/R2; both branches have the same voltage and their currents add. Power P = V × I. The displayed network resistance excludes the switch. An open switch makes the complete circuit resistance effectively infinite.</p></details><button className="btn secondary section-gap" onClick={()=>download("my-circuit-experiment.txt",`${mode.toUpperCase()} CIRCUIT\nSupply: ${volts} V\nR1: ${r1} Ω; R2: ${r2} Ω\nSwitch: ${closed?"closed":"open"}\nCurrent: ${(value.current*1000).toFixed(1)} mA\nMeter ${red} to ${black}: ${reading.toFixed(2)} V\n\nMy observation:\n`)}>Download experiment notes</button><p className="notice small">Learning simulation only. Do not connect this model to mains electricity or use these controls as instructions for testing real equipment. Real components and meters have additional limits and risks.</p>{saved.error&&<p role="alert">{saved.error}</p>}
  </section>;
}
