"use client";
import { useEffect, useState } from "react";
import { cellValue, typingResult, type Sheet } from "@/lib/skills-practice";
import { download, useSaved } from "@/lib/storage";
const passages=["A useful skill grows with practice. Start slowly, check your work, and try again. Small improvements made every day can become real confidence.","Technology can help us learn about the world. Read carefully, protect your private information, and never become a stranger to your own language.","Dear Teacher, I have attached my assignment for your review. Please let me know if any changes are needed. Thank you for your time and guidance."];
const initialSheet:Sheet={B2:"3",C2:"40",D2:"",B3:"5",C3:"10",D3:"",B4:"20",C4:"2",D4:"",D5:""};
const validSheet=(v:unknown):v is Sheet=>!!v&&typeof v==="object"&&Object.keys(initialSheet).every(k=>typeof (v as Sheet)[k]==="string"&&(v as Sheet)[k].length<80);
export default function DigitalPractice(){
  const [tab,setTab]=useState("typing"),[passage,setPassage]=useState(0),[typed,setTyped]=useState(""),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[message,setMessage]=useState("");
  const [subject,setSubject]=useState(""),[body,setBody]=useState(""),[attachment,setAttachment]=useState(false),[emailFeedback,setEmailFeedback]=useState<string[]>([]);
  const sheet=useSaved("practice-sheet",initialSheet,validSheet),target=passages[passage],result=typingResult(target,typed,seconds);
  useEffect(()=>{if(!running)return;const timer=setInterval(()=>setSeconds(s=>s+1),1000);const stop=()=>{if(document.hidden)setRunning(false);};document.addEventListener("visibilitychange",stop);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",stop);};},[running]);
  const finished=typed.length>=target.length||seconds>=60;
  useEffect(()=>{if(!running||!finished)return;const timeout=setTimeout(()=>setRunning(false),0);return()=>clearTimeout(timeout);},[finished,running]);
  function assessEmail(){const checks=[];if(subject.trim().length<8)checks.push("Add a specific subject, such as Assignment submission — Political Science.");if(!/dear|hello|good morning|good afternoon/i.test(body))checks.push("Begin with a respectful greeting.");if(!/assignment|submission|submit|attached/i.test(body))checks.push("Explain why you are writing.");if(!/thank|regards|sincerely/i.test(body))checks.push("Close politely and add a name.");if(body.trim().split(/\s+/).length<20)checks.push("Give enough context: subject, assignment and what response you need.");if(!attachment)checks.push("The task asks for an attachment. Add the simulated file before finishing.");setEmailFeedback(checks.length?checks:["Ready for a human review. Your draft has the basic parts. This check cannot judge tone or factual accuracy."]);}
  return <section className="panel digital-practice"><div className="row between"><div><p className="eyebrow">Everyday skills / real practice</p><h2>Learn it by doing it.</h2></div><span className="tag">Practice, not a test</span></div><div className="tabs" role="group" aria-label="Digital practice">{[["typing","Typing & accuracy"],["sheet","Spreadsheet sandbox"],["email","Email rehearsal"]].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setRunning(false);setMessage("");}}>{name}</button>)}</div>
    {tab==="typing"&&<div className="typing-lab"><div className="practice-stats"><div><strong>{Math.min(seconds,60)}s</strong><small>active time / 60 s</small></div><div><strong>{result.wpm}</strong><small>correct words / minute</small></div><div><strong>{result.accuracy}%</strong><small>accuracy</small></div></div><label>Practice passage<select value={passage} disabled={running} onChange={e=>{setPassage(+e.target.value);setTyped("");setSeconds(0);}}>{passages.map((_,i)=><option key={i} value={i}>Passage {i+1}</option>)}</select></label><p className="typing-target" aria-label={target}>{[...target].map((char,i)=><span aria-hidden="true" key={i} className={i<typed.length?typed[i]===char?"correct":"incorrect":i===typed.length?"cursor":""}>{char}</span>)}</p><label>Type the passage<textarea rows={4} value={typed} disabled={!running||finished} spellCheck={false} autoComplete="off" autoCorrect="off" autoCapitalize="off" onPaste={e=>{e.preventDefault();setMessage("Type this passage yourself to practise. Paste is disabled in this exercise.");}} onChange={e=>setTyped(e.target.value.slice(0,target.length))}/></label><div className="row"><button className="btn" disabled={finished} onClick={()=>setRunning(!running)}>{running?"Pause":seconds?"Resume":"Start practice"}</button><button className="btn secondary" onClick={()=>{setRunning(false);setTyped("");setSeconds(0);setMessage("");}}>Reset</button></div><p className="small muted">A word is measured as five correct characters. Accuracy compares your current text with the passage. Use your own pace; this is not a certified typing result.</p>{finished&&<p className="notice success">Practice complete: {result.wpm} WPM and {result.accuracy}% accuracy. Correctness matters more than speed.</p>}</div>}
    {tab==="sheet"&&<div><p>Build a small stationery budget. Enter <code>=B2*C2</code> in D2, repeat for rows 3 and 4, then use <code>=SUM(D2:D4)</code> in D5. Change a quantity and watch your formulas recalculate.</p><div className="practice-sheet"><table><thead><tr><th scope="col">A / Item</th><th scope="col">B / Quantity</th><th scope="col">C / Price ₹</th><th scope="col">D / Cost ₹</th></tr></thead><tbody>{["Notebooks","Pens","Printed pages"].map((name,i)=><tr key={name}><th scope="row"><small>{i+2}</small> {name}</th>{["B","C","D"].map(col=>{const id=`${col}${i+2}`;const value=cellValue(id,sheet.value);return <td key={id}><input aria-label={`Cell ${id}`} value={sheet.value[id]} maxLength={60} onChange={e=>{sheet.setValue({...sheet.value,[id]:e.target.value});setMessage("");}}/><output>{sheet.value[id]?typeof value==="number"?value.toFixed(2):value:"—"}</output></td>;})}</tr>)}<tr><th colSpan={3} scope="row">5 / Total</th><td><input aria-label="Cell D5" maxLength={60} value={sheet.value.D5} onChange={e=>{sheet.setValue({...sheet.value,D5:e.target.value});setMessage("");}}/><output>{sheet.value.D5?String(cellValue("D5",sheet.value)):"—"}</output></td></tr></tbody></table></div><div className="row section-gap"><button className="btn" onClick={()=>{const good=[2,3,4].every(i=>sheet.value[`D${i}`].replace(/\s/g,"").toUpperCase()===`=B${i}*C${i}`)&&sheet.value.D5.replace(/\s/g,"").toUpperCase()==="=SUM(D2:D4)";setMessage(good?"Great! Your budget uses formulas, so changing quantities updates the total.":"Check that D2–D4 multiply the quantity by the price, and D5 sums D2:D4. Type formulas, not fixed answers.");}}>Check my formulas</button><button className="btn secondary" onClick={()=>{sheet.setValue(initialSheet);setMessage("Sheet reset to the original exercise.");}}>Reset exercise</button></div><details className="section-gap"><summary>Supported formulas and errors</summary><p>This small teaching sheet supports one +, −, * or / operation, cell references, SUM and AVERAGE over one column. It does not run arbitrary code. #DIV/0 means division by zero; #CYCLE means a circular reference; #VALUE means text where a number is expected; #FORMULA means an unsupported formula.</p></details>{sheet.error&&<p role="alert">{sheet.error}</p>}</div>}
    {tab==="email"&&<div className="two-col"><div className="email-brief"><p className="eyebrow">Scenario / assignment submission</p><h3>Send a clear, respectful message.</h3><p>Rehearse submitting an assignment. Include the subject, a short explanation, a request for review, a polite closing and a simulated attachment.</p><p className="notice">Practice only. Nothing is sent. Use a fictional name; do not enter private information.</p><p className="small muted">Recipient: teacher@example.edu (example address)</p></div><div className="email-composer"><label>Subject<input maxLength={160} value={subject} onChange={e=>{setSubject(e.target.value);setEmailFeedback([]);}}/></label><label>Message<textarea rows={8} maxLength={3000} value={body} onChange={e=>{setBody(e.target.value);setEmailFeedback([]);}}/></label><label className="check"><input type="checkbox" checked={attachment} onChange={e=>{setAttachment(e.target.checked);setEmailFeedback([]);}}/> Attach assignment.pdf (simulated, no upload)</label><div className="row"><button className="btn" onClick={assessEmail}>Review my draft</button><button className="btn secondary" onClick={()=>download("practice-email.txt",`PRACTICE DRAFT — NOT SENT\nSubject: ${subject}\n\n${body}\n\n${attachment?"Simulated attachment: assignment.pdf":"No attachment"}`)}>Keep draft</button></div>{emailFeedback.length>0&&<div className="notice" role="status">{emailFeedback.map(text=><p key={text}>{text}</p>)}</div>}</div></div>}
    {message&&<p className="notice" role="status">{message}</p>}
  </section>;
}
