"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import GuitarSimulator from "./guitar-simulator";
import { MusicAudio } from "@/lib/music-audio";
const NOTES=["C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B","C"];
const KEYBOARD=["a","w","s","e","d","f","t","g","y","h","u","j","k"];
const DRUMS=["Kick","Snare","Hi-hat","Clap"];
export default function MusicStudio(){
  const [instrument,setInstrument]=useState("Guitar"),[octave,setOctave]=useState(4),[volume,setVolume]=useState(55),[bpm,setBpm]=useState(80),[metro,setMetro]=useState(false),[beat,setBeat]=useState(0),[active,setActive]=useState(""),[error,setError]=useState("");
  const audio=useRef<MusicAudio|null>(null),flash=useRef<ReturnType<typeof setTimeout>|null>(null);
  const ready=useCallback(async()=>{audio.current??=new MusicAudio();await audio.current.enable();return audio.current;},[]);
  useEffect(()=>{if(audio.current)audio.current.volume=volume/100;},[volume]);
  const play=useCallback(async(index:number)=>{try{const engine=await ready();engine.volume=volume/100;if(instrument==="Piano")engine.tone(440*2**(((octave+1)*12+index-69)/12));else engine.drum(DRUMS[index]);setActive(String(index));if(flash.current)clearTimeout(flash.current);flash.current=setTimeout(()=>setActive(""),180);setError("");}catch{setError("Audio could not start. Check your browser sound settings and tap again.");}},[instrument,octave,volume,ready]);
  useEffect(()=>{if(!metro)return;let count=0;const tick=()=>{audio.current?.tone(count===0?1000:700,.06,"sine");setBeat(count);count=(count+1)%4;};tick();const timer=setInterval(tick,60000/bpm);return()=>clearInterval(timer);},[metro,bpm]);
  useEffect(()=>{const stop=()=>{if(document.hidden)setMetro(false);};document.addEventListener("visibilitychange",stop);return()=>{document.removeEventListener("visibilitychange",stop);if(flash.current)clearTimeout(flash.current);void audio.current?.close();audio.current=null;};},[]);
  useEffect(()=>{if(instrument==="Guitar")return;const key=(e:KeyboardEvent)=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||["INPUT","SELECT","TEXTAREA"].includes((e.target as HTMLElement).tagName))return;const index=instrument==="Piano"?KEYBOARD.indexOf(e.key.toLowerCase()):["z","x","c","v"].indexOf(e.key.toLowerCase());if(index>=0){e.preventDefault();void play(index);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[instrument,play]);
  return <section className="music-studio" aria-label="Music practice studio"><div className="studio-header"><p className="eyebrow">Listen · play · practise</p><h2>Your music studio</h2><p>Explore notes, chords and rhythm with three playable instruments. Tap the controls to start sound.</p><div className="tabs" role="group" aria-label="Choose instrument">{["Guitar","Piano","Drums"].map(name=><button key={name} aria-pressed={instrument===name} onClick={()=>{setInstrument(name);setActive("");}}>{name}</button>)}</div></div>
    {instrument==="Guitar"?<GuitarSimulator/>:<section className="panel instrument-panel"><div className="row between"><h3>{instrument==="Piano"?"A keyboard at your fingertips":"Build a beat"}</h3>{instrument==="Piano"&&<label>Octave <select value={octave} onChange={e=>setOctave(Number(e.target.value))}><option value={3}>3 · low</option><option value={4}>4 · middle</option><option value={5}>5 · high</option></select></label>}</div>
      {instrument==="Piano"?<div className="piano-scroll"><div className="piano-keys" role="group" aria-label="Piano keys">{NOTES.map((note,index)=><button key={index} className={`piano-key ${note.includes("♯")?"black":"white"} ${active===String(index)?"playing":""}`} aria-label={`${note}${octave+(index===12?1:0)}`} onPointerDown={e=>{e.preventDefault();void play(index);}} onClick={e=>{if(e.detail===0)void play(index);}}><span>{note}</span><small>{KEYBOARD[index].toUpperCase()}</small></button>)}</div></div>:<div className="drum-pads">{DRUMS.map((name,index)=><button key={name} className={`drum-pad drum-${index} ${active===String(index)?"playing":""}`} onPointerDown={e=>{e.preventDefault();void play(index);}} onClick={e=>{if(e.detail===0)void play(index);}}><span className="drum-ring"/><strong>{name}</strong><small>{["Z","X","C","V"][index]}</small></button>)}</div>}
      <p className="small muted">{instrument==="Piano"?"Play C–D–E–F–G–A–B–C to hear a major scale. Black keys raise the neighbouring lower note by a semitone. Keyboard shortcuts appear on each key.":"Kick is the low pulse; snare marks an accent; hi-hat keeps subdivisions. Try kick on 1 and 3, snare on 2 and 4, and count evenly."}</p>
    </section>}
    <section className="panel section-gap rhythm-panel"><div><h3>Keep time</h3><p className="small muted">Count 1–2–3–4. Start slowly and keep the gaps between notes even.</p><div className="beat-lights">{[0,1,2,3].map(n=><span key={n} className={metro&&beat===n?"lit":""}>{n+1}</span>)}</div></div><div className="stack"><label>Tempo: {bpm} BPM<input type="range" min="40" max="180" value={bpm} onChange={e=>setBpm(Number(e.target.value))}/></label><label>Studio volume: {volume}%<input type="range" min="0" max="100" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><button className="btn" onClick={async()=>{try{const engine=await ready();engine.volume=volume/100;setMetro(!metro);}catch{setError("Audio could not start. Tap again after enabling browser sound.");}}}>{metro?"Stop metronome":"Start metronome"}</button></div></section>
    <section className="panel section-gap"><h3>{instrument} practice guide</h3>{instrument==="Guitar"?<><details open><summary>Understand the strings and frets</summary><p>Standard tuning from the thickest string to the thinnest is E–A–D–G–B–E. Fret 0 means an open string; × means muted. Each fret raises the pitch by one semitone. The numbers shown here are fret positions, not finger numbers.</p></details><details><summary>Your first chord changes</summary><p>Select Em and strum once on each beat at 60 BPM. After four beats, switch to G. Repeat until the timing is steady. Next try G–C–D–G, spending four beats on each chord.</p></details><details><summary>Down and up strumming</summary><p>A downstroke goes from low E towards high E; an upstroke goes the other way. Count “1 and 2 and 3 and 4 and”. Use downstrokes on the numbers and upstrokes on “and”. Muted strings are skipped.</p></details></>:instrument==="Piano"?<><details open><summary>Find middle C and learn a scale</summary><p>Choose octave 4: the first C is middle C. Play C D E F G A B C slowly, then return in reverse. First use one note per metronome beat; then try two notes per beat.</p></details><details><summary>Build three-note chords</summary><p>A C major chord contains C, E and G. A minor contains A, C and E. Tap the three notes together on a touch screen, or play them one after another to hear an arpeggio. Compare their different character.</p></details><details><summary>Practise a small melody</summary><p>Play C–D–E–C, then E–F–G. Repeat and listen for an even rhythm. Make your own answer phrase using G–E–D–C. The goal is timing and listening, not speed.</p></details></>:<><details open><summary>Start with a steady pulse</summary><p>Set the metronome to 70 BPM. Tap Kick on beats 1 and 3, and Snare on beats 2 and 4. Repeat for four bars before increasing the tempo.</p></details><details><summary>Add the hi-hat</summary><p>Count “1 and 2 and 3 and 4 and”. Tap Hi-hat on each number and each “and”. Add the kick and snare pattern with the other hand. Start at a tempo where both hands stay relaxed.</p></details><details><summary>Make a fill</summary><p>Keep three bars of your basic rhythm, then play four evenly spaced snare hits in the fourth bar. Return to Kick on beat 1. A fill should bring you back to the pulse.</p></details></>}</section>
    {error&&<p className="notice error" role="alert">{error}</p>}<p className="small muted">Sounds are synthesized for practice. Guitar has its own volume control. No microphone or recording permission is needed.</p>
  </section>;
}
