"use client";
import {useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/shell';
import {tracks} from '@/data/lessons';
import {emptyResults,isResults} from '@/components/quiz';
import {download,emptyList,isStringList,useSaved} from '@/lib/storage';
export default function Progress(){const lessons=useSaved('lessons',emptyList,isStringList);const topics=useSaved('topics',emptyList,isStringList);const bookmarks=useSaved('bookmarks',emptyList,isStringList);const results=useSaved('results',emptyResults,isResults);const [message,setMessage]=useState('');
 async function restore(file?:File){if(!file)return;try{if(file.size>2*1024*1024)throw Error('Choose a backup smaller than 2 MB.');const x=JSON.parse(await file.text());if(x?.version!==1||!isStringList(x.lessons)||!isStringList(x.topics)||!isStringList(x.bookmarks)||!isResults(x.results))throw Error('Choose a valid progress backup from this hub.');if(!confirm('Replace your current learning progress with this backup?'))return;lessons.setValue(x.lessons);topics.setValue(x.topics);bookmarks.setValue(x.bookmarks);results.setValue(x.results);setMessage('Progress restored.');}catch(e){setMessage(e instanceof Error?e.message:'Restore failed.');}}
 return <Shell eyebrow="My progress" title="One step at a time." intro="A record of what you have studied on this browser. Keep going, revisit a tricky topic or pick a new skill."><div className="grid-cards">{Object.entries(tracks).map(([id,t])=>{const count=t.lessons.filter(l=>lessons.value.includes(l.id)).length;const sessions=results.value.filter(r=>r.lab===id);return <section className="panel" key={id}><p className="eyebrow">{id}</p><h2>{count} / {t.lessons.length} lessons</h2><progress max={t.lessons.length} value={count} aria-label={`${id} progress`}/><p className="small muted">{sessions.length} practice or test sessions</p><Link href={`/${id}`} className="btn secondary">Continue learning →</Link></section>})}<section className="panel"><p className="eyebrow">College hub</p><h2>{topics.value.length} topics studied</h2><p className="muted">{bookmarks.value.length} bookmarked papers</p><Link href="/college" className="btn secondary">Open my subjects →</Link></section></div>
 <section className="panel section-gap"><h2>Recent sessions</h2>{results.value.length===0?<p className="muted">Finish a quiz in any learning lab to see your result here.</p>:<div className="stack">{results.value.slice(-20).reverse().map(r=><div className="row between" key={r.id}><span><strong className="capitalize">{r.lab}</strong><span className="small muted"> · {r.mode} · {r.date.slice(0,10)}</span></span><span className="tag">{r.score} / {r.total} · {Math.round(r.score/r.total*100)}%</span></div>)}</div>}<p className="small muted">Up to 100 sessions are kept. These are learning records, not certificates.</p></section>
 <section className="panel section-gap"><h2>Keep a copy of your progress</h2><p className="muted">This backup includes lesson completion, college checklists, bookmarks and quiz results. Download coding projects in the Coding Lab and notebooks in the Study Lab. Paper notes have their own download button in the College Hub.</p><button className="btn" onClick={()=>download('skills-hub-progress.json',JSON.stringify({version:1,lessons:lessons.value,topics:topics.value,bookmarks:bookmarks.value,results:results.value},null,2),'application/json')}>Download progress backup</button><div className="section-gap"><label htmlFor="restore-progress">Restore progress (.json)</label><input id="restore-progress" type="file" accept=".json,application/json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value='';}}/></div><p role="status">{message}</p>{[lessons.error,topics.error,bookmarks.error,results.error].filter(Boolean).slice(0,1).map(e=><p className="notice error" role="alert" key={e}>{e}</p>)}</section></Shell>;
}
