export type Code = { html:string; css:string; js:string };
export function isCode(v:unknown):v is Code {return !!v && typeof v==='object' && ['html','css','js'].every(k=>typeof (v as Record<string,unknown>)[k]==='string');}
export function makeDocument(code:Code,preview=false,channel="trc-preview"){
 const js=code.js.replace(/<\/script/gi,'<\\/script');
 const css=code.css.replace(/<\/style/gi,'<\\/style');
 const protection=preview?`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; form-action 'none'; base-uri 'none';">`:'';
 const errors=preview?`<script>(function(){var count=0;function send(level,args){if(count++>120)return;var text=args.map(function(v){try{return typeof v==='string'?v:JSON.stringify(v);}catch{return String(v);}}).join(' ').slice(0,2000);parent.postMessage({channel:${JSON.stringify(channel)},level:level,text:text},'*');}['log','warn','error','info'].forEach(function(level){var original=console[level];console[level]=function(){send(level,Array.from(arguments));original.apply(console,arguments);};});window.addEventListener('error',function(e){send('error',[e.message+' (line '+e.lineno+')']);});window.addEventListener('unhandledrejection',function(e){send('error',['Promise: '+String(e.reason)]);});window.addEventListener('securitypolicyviolation',function(e){send('warn',['Preview blocked: '+e.violatedDirective]);});})();<\/script>`:'';
 return `<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My coding project</title>${protection}<style>${css}</style></head><body>${errors}${code.html}<script>${js}<\/script></body></html>`;
}
