"use client";
import {useState} from 'react';
import Shell from '@/components/shell';
import {projects,type ProjectKey,type Tab} from '@/data/projects';
import {download,useSaved} from '@/lib/storage';
import {isCode,makeDocument,type Code} from '@/lib/code';
function Workspace({projectKey}:{projectKey:ProjectKey}){
 const draft=useSaved<Code>(`code:${projectKey}`,projects[projectKey],isCode);
 const [tab,setTab]=useState<Tab>('html');
 const [preview,setPreview]=useState(()=>makeDocument(projects[projectKey],true));
 const [run,setRun]=useState(0);const [message,setMessage]=useState('');
 function runCode(){setPreview(makeDocument(draft.value,true));setRun(run+1);setMessage('Preview updated.');}
 async function importFile(file?:File){if(!file)return;try{if(file.size>2*1024*1024)throw Error('Use a project JSON file smaller than 2 MB.');const parsed:unknown=JSON.parse(await file.text());if(!isCode(parsed))throw Error('This is not a coding project. Choose a JSON backup with HTML, CSS and JavaScript.');if(!confirm('Replace this project’s saved code with the imported file?'))return;draft.setValue({html:parsed.html,css:parsed.css,js:parsed.js});setPreview(makeDocument(parsed,true));setRun(run+1);setMessage('Project imported.');}catch(e){setMessage(e instanceof Error?e.message:'Could not import this file.');}}
 return <><p className="notice small">Edits save in this browser. Press Run code to update the preview, including after reopening a saved project. Download a project backup to move between devices.</p><div className="two-col section-gap"><section className="panel"><div className="row between"><h2>{projects[projectKey].name}</h2><span className="tag">Editor</span></div><div className="tabs" role="group" aria-label="Code language">{(['html','css','js'] as Tab[]).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='js'?'JavaScript':t.toUpperCase()}</button>)}</div><label htmlFor="code-editor" className="sr-only">{tab.toUpperCase()} code</label><textarea id="code-editor" className="code-editor" spellCheck={false} value={draft.value[tab]} onChange={e=>draft.setValue({...draft.value,[tab]:e.target.value})}/><div className="row section-gap"><button className="btn" onClick={runCode}>Run code ▶</button><button className="btn secondary" onClick={()=>{if(confirm('Reset this project to its starter? Your saved edits will be replaced.')){draft.setValue(projects[projectKey]);setPreview(makeDocument(projects[projectKey],true));setRun(run+1);setMessage('Starter restored.');}}}>Reset starter</button></div></section><section className="panel"><div className="row between"><h2>Live preview</h2><span className="tag">Sandbox</span></div><iframe key={run} title="Coding preview" sandbox="allow-scripts" srcDoc={preview} style={{height:520}}/><p className="small muted">The preview runs separately from the hub. Network requests, external scripts and external images are blocked here.</p></section></div>
 <section className="panel section-gap"><h2>Keep what you build</h2><div className="row"><button className="btn" onClick={()=>download(`${projectKey}.html`,makeDocument(draft.value),'text/html')}>Download website (.html)</button><button className="btn secondary" onClick={()=>download(`${projectKey}-project.json`,JSON.stringify(draft.value,null,2),'application/json')}>Download project backup</button></div><div className="section-gap"><label htmlFor="project-import">Restore a project backup (.json, up to 2 MB)</label><input id="project-import" type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></div><p className="small muted">Your HTML download contains the code you wrote. Open and share only code you trust.</p><p role="status">{message}</p>{draft.error&&<p role="alert" className="notice error">{draft.error}</p>}</section></>;
}
export default function Coding(){const [selected,setSelected]=useState<ProjectKey>('calculator');return <Shell eyebrow="Coding lab" title="An idea. A little code. Your creation." intro="Choose a starter, change something and see what happens. HTML is the content, CSS is the design and JavaScript is the behaviour."><label htmlFor="starter">Choose a starter project</label><select id="starter" value={selected} onChange={e=>setSelected(e.target.value as ProjectKey)}>{Object.entries(projects).map(([key,p])=><option key={key} value={key}>{p.name} — {p.description}</option>)}</select><div className="section-gap"><Workspace key={selected} projectKey={selected}/></div><section className="panel section-gap"><h2>Try these challenges</h2><ol className="list-decimal pl-5 space-y-3 muted"><li>Change the heading and colours without changing the behaviour.</li><li>Add one feature, then explain each line that makes it work.</li><li>Enter an unexpected value. Can you make the error message clearer?</li><li>Download your website and open it in a browser.</li></ol><details><summary>Ask an AI tool for help</summary><p>I am a beginner. Help me change this browser-only project. Give HTML, CSS and JavaScript separately, without external libraries. Explain each change in simple English and give me one thing to try myself.</p></details></section></Shell>}
